# Generated by Django 5.1.4 on 2025-01-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0009_medicationrequest_authored_on"),
        ("emr", "0011_enable_auto_time"),
    ]

    operations = []
